version: '1.0.{build}'

image: Visual Studio 2017

platform:
  - x64
 
configuration:
  - Release
  - Debug

install:
    - git submodule update --init --recursive

before_build:
    - cmake -G "Visual Studio 15 2017 Win64" .

build:
  project: $(APPVEYOR_BUILD_FOLDER)\$(APPVEYOR_PROJECT_NAME).sln

test_script:
  - '%APPVEYOR_BUILD_FOLDER%\%CONFIGURATION%\tests.exe'
notifications:
- provider: Email
  to:
  - antongr2001@gmail.com
  subject: homework04 (appveyor)
  message: ะะบ! Build success! - ci.appveyor.com
  on_build_success: true
  on_build_failure: false
  on_build_status_changed: false
