image: Visual Studio 2019


build_script:
 - cmd: cd hello_world_application
 - cmd: cmake -H. -B_build
 - cmd: cmake --build _build
 - cmd: cmake --build _build --target hello_world
 - cmd: _build\Debug\hello_world.exe
 - cmd: echo "Testing hello_world is done"
 - cmd: cd ..
 - cmd: cd solver_application
 - cmd: cmake -H. -B_build
 - cmd: cmake --build _build
 - cmd: cmake --build _build --target solver
 - cmd: echo "Testing solver is done"
version: 1.0.{build}
build:
  verbosity: minimal
notifications:
- provider: Email
  to:
  - antongr2001@gmail.com
  subject: homework04
  message: От ci.appveyor.com
  on_build_success: true
  on_build_failure: false
  on_build_status_changed: false
